Introduce Recommended access order (RAO) via EA
LinearTapeFileSystem/ltfs pull request #287
Opened 2021-05-26 06:31 UTC by y-sasn

# Summary of changes

Introduce Recommended access order (RAO) support via EA by `ltfs.vendor.IBM.rao`.

# Description

This update introduce the support of the RAO (GRAO, RRAO) command, which was introduced from LTO-9.
Only linux scsi generic (sg) driver is supported in this fix.

## How to use

1. Set a file path to a correct GRAO Parameter Data via VEA on mount point.
2. A `xxx.out` file containing the RAO List will be made in the same directory.

example:
```
attr -s ltfs.vendor.IBM.rao -V ~/xxx <mount dir>
# The result will be created in `~/xxx.out`
```

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have confirmed my fix is effective or that my feature works

2021-05-26 07:10 UTC, piste-jp-ibm commented
This is not good for merging to `v2.4-stable` because you already merged the changes to `master` on your branch.

I think it is impossible to merge your branch to `v2.4-stable` anymore. Could you create another PR to merge your changes to `master` ?

After that, I will try to merge it to `v2.4-stable` by cherry-pick.

2021-05-26 07:10 UTC, piste-jp-ibm requested changes
See my comment on conversation thread.

2021-05-26 12:23 UTC, piste-jp-ibm commented
Can I close this one ?

2021-05-27 01:41 UTC, y-sasn commented
Yes, I think we can. Closing PR.

2021-05-27 01:41 UTC, closed without merging

2022-01-17 03:30 UTC, sevenever commented on src/tape_drivers/linux/lin_tape/lin_tape_ibmtape.c
> +	return logpage.len;
Before this change, the ret value of lin_tape_ibmtape_logsense() is actually the ret code of ioctl SIOC_LOG_SENSE10_PAGE. With this change, the ret value was changed to length of data in buffer, which dooms to fail the check below in [lin_tape_ibmtape_remaining_capacity()](https://github.com/LinearTapeFileSystem/ltfs/pull/287/commits/1fbde528e7aa0ce2a253fbd8511dd91064c66cd6#diff-72823ff6a06c061d93257e41fe1a0436acb899d0b7872f8d75372cd119f4f134R3389), even if the IOCTL is actually succeed.
We are hitting "LTFS30457I Cannot get remaining capacity: get log page 0x17 failed ..." error on an IBM tape autoloader. I think this is probably the root cause?