Changed flags for _ltfs_search_index_wp
LinearTapeFileSystem/ltfs pull request #480
Opened 2024-08-27 02:22 UTC by amissael95

# Summary of changes

This pull request includes following changes or fixes. 

- Fix of issue #479
- Changed flags for `_ltfs_search_index_wp`

# Description

When a tape cartridge with a write permanent error is trying to be mounted and the MAM (cartridge memory) attribute of the Index Partion (IP) stores a generation number **different** than the MAM attribute of the Data Partition (DP), the mount process fails even when ltfs can still search for the index in the other partition. 

The code that belongs to the logic that handles WP happens on IP, defined "can_skip_ip" flag as false and it shall be **true**. On the other hand, the code that handles WP happens on DP, defined the "can_skip_ip" as true and it should be false. The logic is not adjusted accordingly. 

Fixes #issue_no

## Type of change
- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have confirmed my fix is effective or that my feature works

2024-08-27 03:13 UTC, piste-jp commented
I would like to ask you the things below.

1. Please test your code on your bench. File backend might be helpful for this kind of issue
2. Please clarify this PR shall be merged to `v2.4-stable` branch or not
3. Please set reviewer(s) for having review comments

2024-08-29 00:42 UTC, piste-jp commented
@amissael95 ,

Could you take care about my previous comment about PR #480 ?

2024-09-10 02:32 UTC, piste-jp commented
@juliocelon , @perezle ,

Could you handle this?

It looks issue #479 and it's fix (this PR) come from a customer. I don't know I just push this only on master branch.

2024-09-23 17:08 UTC, perezle approved these changes
I approve. The skip flag is set to true to try again on the next index search. Thanks for this catch.

2024-09-24 01:16 UTC, piste-jp requested changes
@juliocelon , @perezle ,

Both of you MUST NOT merge this PR to the stable branch!!!! This PR ruins the stable branch completely.

@amissael95 ,

Did you merge `v2.4-stable` branch to your dev branch (and push)?

It is completely wrong operation. Please fix your PR.





Why didi you merge

2024-09-24 01:23 UTC, piste-jp commented
> You mentioned that the file backend might be helpful to the test this kind of issue. Did you mean to use "ltfs.vendor.IBM.forceErrorWrite" extended attribute ? I was planning to use ITDT to test this change, but could you provide me more details in case I use a file backend?

I believe a tape which has following condition is needed for your test.

  1. The tape has a write perm while LTFS was writing an index on IP
    - this write perm handling shall be successfully done and the tape is closed cleanly
  2. `VCR` value returned from a tape drive is different from which is stored on MAM

I'm not sure how you can create a tape both condition was met. But you can use ITDT if you know how to do it obviously.

My intention is the file backend manages MAM and VCR on its file, so you can create those condition with editing file backend files (while ltfs is not running).

2024-09-24 01:35 UTC, amissael95 commented
> @juliocelon , @perezle ,
> 
> Both of you MUST NOT merge this PR to the stable branch!!!! This PR ruins the stable branch completely.
> 
> @amissael95 ,
> 
> Did you merge `v2.4-stable` branch to your dev branch (and push)?
> 
> It is completely wrong operation. Please fix your PR.
> 
> Why didi you merge

@piste-jp,

My branch was created from master branch so all these conflicts are because the differences between master and `v2.4-stable` branch, I did not merge or push it with `v2.4-stable` . I will solve this problem by making the fix change based on/from the `v2.4-stable` branch.

Regards

2025-01-21 16:46 UTC, amissael95 commented
Closing PR to perform change from right branch: `v2.4-stable`

2025-01-21 16:46 UTC, closed without merging